### ISSUE TITLE
[BUG] Searxng: URI illegal character

### ISSUE THREAD

**Issue by Martin7-1** [langchain4j/langchain4j-community#35]
## Describe the bug

`langchain4j-community-web-search-engine-searxng` can't handle illegal character in URI properly.

## Log and Stack trace

```
java.lang.IllegalArgumentException: Illegal character in fragment at index 119: https://www.linkedin.com/pulse/introduction-langchain4j-supercharging-java-llms-ibrahim-jimoh-kyj4f#:~:text=LangChain4j is a groundbreaking Java,by Python and JavaScript libraries.
	at java.base/java.net.URI.create(URI.java:906)
	at dev.langchain4j.community.web.search.searxng.SearXNGWebSearchEngine.toWebSearchOrganicResult(SearXNGWebSearchEngine.java:59)
	at dev.langchain4j.community.web.search.searxng.SearXNGWebSearchEngine.lambda$search$1(SearXNGWebSearchEngine.java:79)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.community.web.search.searxng.SearXNGWebSearchEngine.search(SearXNGWebSearchEngine.java:79)
	at dev.langchain4j.web.search.WebSearchEngine.search(WebSearchEngine.java:15)
	at dev.langchain4j.web.search.WebSearchEngineIT.should_search(WebSearchEngineIT.java:22)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 119: https://www.linkedin.com/pulse/introduction-langchain4j-supercharging-java-llms-ibrahim-jimoh-kyj4f#:~:text=LangChain4j is a groundbreaking Java,by Python and JavaScript libraries.
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3147)
	at java.base/java.net.URI$Parser.parse(URI.java:3191)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 18 more
```

## Minimal Example to Reproduce

```java
String url = "https://www.linkedin.com/pulse/introduction-langchain4j-supercharging-java-llms-ibrahim-jimoh-kyj4f#:~:text=LangChain4j is a groundbreaking Java,by Python and JavaScript libraries."

URI.create(url)
```

## Expected behavior

Handle illegal character properly. (Remove or encode them?)

## Please complete the following information:
- LangChain4j Community version: 0.36.2
- LangChain4j Community Component you used (e.g. `langchain4j-community-clickhouse`): `langchain4j-community-web-search-engine-searxng`
- Java version: 17
- Spring Boot version (if applicable): 

## Additional context

/cc @bnayfeh

**Comment by bnayfeh** [comment]
I think the IllegalArgumentException is actually the right thing to happen in this case.  Basically, the exception indicates the real problem (an invalid URL which should be corrected) and masking the issue by silently "correcting" the URL could cause bigger unforeseen issues in the future.

**Comment by Martin7-1** [comment]
What about this case?

https://www.linkedin.com/pulse/introduction-langchain4j-supercharging-java-llms-ibrahim-jimoh-kyj4f#:~:text=LangChain4j is a groundbreaking Java,by Python and JavaScript libraries.

I think it's a correct URL but is not a valid URI because it contains `#:~:text=LangChain4j is a groundbreaking Java,by Python and JavaScript libraries.` which is a text fragment (`#` is a [fragment identifier component](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5), but `~:` is a special identifier for Chrome).

**Comment by bnayfeh** [comment]
I can test and confirm this a bit later today, but I'm guessing the issue here is not so much the special identifier for Chrome ("~:") but rather the spaces in the text fragment after it.  In general, especially with general libraries such as this, I believe the responsibility should be on the caller to ensure the URL is valid and not to rely on hidden magic to fix things up.  The challenge is that a "fix" in the background may result in an invalid URL on the server and be very difficult for people to debug.  In the current scenario, getting an exception for a URL that is, in fact, invalid due to the spaces is very clear for everyone.

**Comment by Martin7-1** [comment]
Hmmm...But the URL is returned by the web search engine not the caller, I'm not sure if this is due to searxng choosing to return a text fragment or something else. I'm wondering whether Searxng has an option to just get valid URL without fragment or not. Could you please check it?

I'm sure the problem is because the `#` character, because I temporarily fix it by removing the substring after the `#` character and it works fine.

I think the except result is to just return URL and do not contain any text fragment. WDYT?

**Comment by bnayfeh** [comment]
I confirmed that the issue is with the spaces and that the other characters are fine.  If I encode just the spaces, it works.  My concern with removing the '#' and things after it is that I think it would break links for certain SPAs.  Ideally, searxng should not return links containing spaces, as they are illegal, but we can mitigate it by encoding the space characters for now.

**Comment by Martin7-1** [comment]
Great! I think encode space is OK and won't introduce breaking change. Could you please help fix it? (`FIXME` in the `SearXNGWebSearchEngine`)

**Comment by bnayfeh** [comment]
Submitted a draft PR.  I'm traveling at the moment and don't have my environment where I can run the integration tests but let me know if you can.
